# basic options
title: TheBarstadBlog
author: Johannes Barstad
email: johannesbarstad92@gmail.com
description: Private blog of Johannes Barstad
github_username: Barstad
linkedin_username: 

# Build settings
markdown: kramdown
theme: minima

social-network-links:
  linkedin: johannesandreasbarstad

share-links-active:
  linkedin: true
